# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PortalBiblioteca.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'PortalBiblioteca.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16PortalBiblioteca.proto\x12\nbiblioteca\"7\n\x07Usuario\x12\x0b\n\x03\x63pf\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tbloqueado\x18\x03 \x01(\x08\"U\n\x05Livro\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\r\n\x05\x61utor\x18\x03 \x01(\t\x12\r\n\x05total\x18\x04 \x01(\x05\x12\x10\n\x08restante\x18\x05 \x01(\x05\"%\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1b\n\rIdentificador\x12\n\n\x02id\x18\x01 \x01(\t\"d\n\x0cUsuarioLivro\x12*\n\x07usuario\x18\x01 \x01(\x0b\x32\x19.biblioteca.Identificador\x12(\n\x05livro\x18\x02 \x01(\x0b\x32\x19.biblioteca.Identificador\"[\n\x10UsuarioBloqueado\x12$\n\x07usuario\x18\x01 \x01(\x0b\x32\x13.biblioteca.Usuario\x12!\n\x06livros\x18\x02 \x03(\x0b\x32\x11.biblioteca.Livro\"\x1c\n\x08\x43riterio\x12\x10\n\x08\x63riterio\x18\x01 \x01(\t\"\x07\n\x05Vazia2\xa9\x04\n\x10PortalBiblioteca\x12\x45\n\x11RealizaEmprestimo\x12\x18.biblioteca.UsuarioLivro\x1a\x12.biblioteca.Status\"\x00(\x01\x12\x44\n\x10RealizaDevolucao\x12\x18.biblioteca.UsuarioLivro\x1a\x12.biblioteca.Status\"\x00(\x01\x12;\n\x10\x42loqueiaUsuarios\x12\x11.biblioteca.Vazia\x1a\x12.biblioteca.Status\"\x00\x12\x39\n\x0eLiberaUsuarios\x12\x11.biblioteca.Vazia\x1a\x12.biblioteca.Status\"\x00\x12N\n\x17ListaUsuariosBloqueados\x12\x11.biblioteca.Vazia\x1a\x1c.biblioteca.UsuarioBloqueado\"\x00\x30\x01\x12\x42\n\x16ListaLivrosEmprestados\x12\x11.biblioteca.Vazia\x1a\x11.biblioteca.Livro\"\x00\x30\x01\x12>\n\x12ListaLivrosEmFalta\x12\x11.biblioteca.Vazia\x1a\x11.biblioteca.Livro\"\x00\x30\x01\x12<\n\rPesquisaLivro\x12\x14.biblioteca.Criterio\x1a\x11.biblioteca.Livro\"\x00\x30\x01\x42*\n&br.ufu.facom.gbc074.projeto.bibliotecaP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PortalBiblioteca_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&br.ufu.facom.gbc074.projeto.bibliotecaP\001'
  _globals['_USUARIO']._serialized_start=38
  _globals['_USUARIO']._serialized_end=93
  _globals['_LIVRO']._serialized_start=95
  _globals['_LIVRO']._serialized_end=180
  _globals['_STATUS']._serialized_start=182
  _globals['_STATUS']._serialized_end=219
  _globals['_IDENTIFICADOR']._serialized_start=221
  _globals['_IDENTIFICADOR']._serialized_end=248
  _globals['_USUARIOLIVRO']._serialized_start=250
  _globals['_USUARIOLIVRO']._serialized_end=350
  _globals['_USUARIOBLOQUEADO']._serialized_start=352
  _globals['_USUARIOBLOQUEADO']._serialized_end=443
  _globals['_CRITERIO']._serialized_start=445
  _globals['_CRITERIO']._serialized_end=473
  _globals['_VAZIA']._serialized_start=475
  _globals['_VAZIA']._serialized_end=482
  _globals['_PORTALBIBLIOTECA']._serialized_start=485
  _globals['_PORTALBIBLIOTECA']._serialized_end=1038
# @@protoc_insertion_point(module_scope)
